### ISSUE TITLE
Daily part

### ISSUE THREAD

**Issue by RohinRajSingh** [kshitizrohilla/weather-app-using-openweathermap-api#4]
![dailyissue](https://github.com/user-attachments/assets/97dd83da-1dfb-4242-8c52-168d6d2de3ff)

this part is same whats the purpose of it?

**Comment by kshitizrohilla** [comment]
Hey @RohinRajSingh This container was meant to show the weekly forecast. Just pushed the changes. It will now show the upcoming 6-day forecast, including today. Thanks :)
